import type { UticQuestao } from "./types";

export const QUESTOES_E07B: UticQuestao[] = [
  {
    id: 52,
    eixoId: "E07",
    eixo: "Suporte, Atendimento e Service Desk",
    tagFonte: "TAG Macroárea: Suporte, Atendimento e Service Desk / Gestão de Chamados",
    macroarea: "Suporte, Atendimento e Service Desk",
    microarea: "Gestão de Chamados",
    enunciado: "Na gestão de incidentes e requisições da Unidade de Tecnologia da Informação e Comunicação (UTIC), a organização da fila de atendimento deve adotar uma estratégia que favoreça a continuidade dos serviços institucionais. Nesse sentido, recomenda-se:",
    opcoes: [
      { id: "q52_a", texto: "Distribuir aleatoriamente as solicitações entre os analistas, utilizando a alternância automática de carga para reduzir a fadiga cognitiva e evitar a sobrecarga dos especialistas." },
      { id: "q52_b", texto: "Escalonar os chamados de acordo com seu nível de criticidade, destinando recursos diferenciados para garantir o cumprimento dos Acordos de Nível de Serviço (SLA) aplicáveis a cada categoria." },
      { id: "q52_c", texto: "Atender rigorosamente pela ordem de abertura, conforme o método First-In, First-Out, considerando que a igualdade temporal entre os setores assegura padronização e previsibilidade às métricas." },
      { id: "q52_d", texto: "Priorizar requisições de baixa complexidade e rápida execução, com o objetivo principal de diminuir o volume acumulado de tickets e melhorar imediatamente os indicadores de produtividade." },
      { id: "q52_e", texto: "Concentrar os esforços nos incidentes de alta severidade, iniciando o atendimento das demais solicitações somente depois da estabilização completa da infraestrutura crítica." },
      { id: "q52_f", texto: "Não sei, desconheço o conteúdo.", naoSei: true },
    ],
  },
  {
    id: 53,
    eixoId: "E07",
    eixo: "Suporte, Atendimento e Service Desk",
    tagFonte: "TAG Macroárea: Suporte, Atendimento e Service Desk / Suporte Nível 1, 2 e 3",
    macroarea: "Suporte, Atendimento e Service Desk",
    microarea: "Suporte Nível 1, 2 e 3",
    enunciado: "Em uma estrutura de suporte técnico organizada em camadas — níveis 1, 2 e 3 —, as atribuições são distribuídas para aumentar a eficiência no tratamento de incidentes e requisições, conforme a complexidade e a especialização exigidas. Assinale a alternativa que caracteriza corretamente a diferença essencial entre esses níveis.",
    opcoes: [
      { id: "q53_a", texto: "O Nível 2 é responsável pelo desenvolvimento de novas funcionalidades e pela implantação de projetos, enquanto o Nível 3 atua exclusivamente na manutenção de redes e servidores." },
      { id: "q53_b", texto: "A hierarquia é definida pela urgência operacional, cabendo ao Nível 1 tratar as demandas mais críticas e ao Nível 3 solucionar ocorrências que não exigem resposta imediata." },
      { id: "q53_c", texto: "O Nível 1 realiza a triagem, o registro e a solução de incidentes simples ou associados a procedimentos padronizados, encaminhando ao Nível 2 os casos que demandem análise técnica mais aprofundada." },
      { id: "q53_d", texto: "Os três níveis possuem atribuições e autoridade equivalentes, diferenciando-se somente pelos turnos de trabalho para assegurar a continuidade do atendimento." },
      { id: "q53_e", texto: "A distinção decorre apenas da experiência profissional dos agentes, sem delimitação formal de competências ou de complexidade entre as camadas de suporte." },
      { id: "q53_f", texto: "Não sei, desconheço o conteúdo.", naoSei: true },
    ],
  },
  {
    id: 54,
    eixoId: "E07",
    eixo: "Suporte, Atendimento e Service Desk",
    tagFonte: "Sem TAG explícita no documento-fonte — questão posicionada no bloco de Suporte, Atendimento e Service Desk",
    macroarea: "Suporte, Atendimento e Service Desk",
    microarea: "Conformidade no Atendimento",
    enunciado: "No contexto da governança de serviços de TI, a conformidade (compliance) no atendimento assegura que as operações estejam alinhadas a normas, políticas e boas práticas estabelecidas. Considerando os princípios que regem essa área, analise as seguintes afirmações: I. A rastreabilidade é um requisito fundamental, devendo todos os atendimentos ser registrados em sistema apropriado para possibilitar auditoria e monitoramento. II. As políticas e procedimentos formalizados de atendimento devem ser observados pela equipe, assegurando padronização e aderência aos controles definidos. III. Em situações excepcionais, desvios pontuais dos procedimentos padrão podem ser tolerados, desde que devidamente autorizados, justificados e documentados para preservar a integridade do processo. Com base na análise, assinale a alternativa correta.",
    opcoes: [
      { id: "q54_a", texto: "Apenas a afirmação I está correta." },
      { id: "q54_b", texto: "As afirmações I e II estão corretas." },
      { id: "q54_c", texto: "As afirmações II e III estão corretas." },
      { id: "q54_d", texto: "Todas as afirmações estão corretas." },
      { id: "q54_e", texto: "Todas as afirmações estão incorretas." },
      { id: "q54_f", texto: "Não sei, desconheço o conteúdo.", naoSei: true },
    ],
  },
  {
    id: 55,
    eixoId: "E07",
    eixo: "Suporte, Atendimento e Service Desk",
    tagFonte: "TAG Macroárea: Suporte, Atendimento e Service Desk / Prevenção de Recorrência",
    macroarea: "Suporte, Atendimento e Service Desk",
    microarea: "Prevenção de Recorrência",
    enunciado: "Uma avaliação do Service Desk da UTIC demonstra que aproximadamente 30% do volume total de chamados corresponde a apenas 5 tipos de problemas recorrentes. Diante dessa concentração, e considerando a otimização dos recursos e a melhoria contínua do serviço, assinale a alternativa que apresenta a estratégia de gestão mais adequada e compatível com as boas práticas de Governança de TI.",
    opcoes: [
      { id: "q55_a", texto: "Encaminhar os problemas recorrentes a um núcleo técnico especializado, transferindo-lhe a responsabilidade pela análise aprofundada e pela proposição de soluções, de modo que o Service Desk possa concentrar-se no fluxo contínuo de novas demandas, estratégia que otimiza a alocação de competências sem onerar a camada inicial de atendimento." },
      { id: "q55_b", texto: "Reconhecer a concentração de 30% dos chamados em 5 tipos como fenômeno inerente à operação de suporte, preservando os processos vigentes e redirecionando eventuais esforços de melhoria para incidentes de maior criticidade momentânea, uma vez que a recorrência em si não compromete os indicadores globais de desempenho." },
      { id: "q55_c", texto: "Ampliar o contingente de analistas do Nível 1, elevando a capacidade de resposta imediata e assegurando que os tempos de atendimento permaneçam dentro dos patamares contratuais, sem necessidade de revisão dos procedimentos de tratamento, pois o incremento de recursos humanos compensa a repetição de ocorrências." },
      { id: "q55_d", texto: "Implantar uma ação estruturada de Gestão de Problemas (Problem Management), investigando e eliminando as causas raiz dos 5 problemas recorrentes, destinando recursos especializados ao desenvolvimento de soluções permanentes e utilizando a redução desses chamados como indicador-chave de desempenho." },
      { id: "q55_e", texto: "Manter o tratamento de cada chamado como um incidente isolado, reforçando os procedimentos de registro e priorização, sem instituir uma iniciativa específica para examinar padrões de recorrência." },
      { id: "q55_f", texto: "Não sei, desconheço o conteúdo.", naoSei: true },
    ],
  },
];
