import type { UticQuestao } from "./types";

export const QUESTOES_E08: UticQuestao[] = [
  {
    id: 56,
    eixoId: "E08",
    eixo: "Liderança e Competências Transversais",
    tagFonte: "TAG Macroárea: Liderança, Processos e Competências Transversais / Liderança Técnica",
    macroarea: "Liderança, Processos e Competências Transversais",
    microarea: "Liderança Técnica",
    enunciado: "Um gerente da UTIC identifica na equipe sinais de desmotivação, acúmulo de férias e elevada rotatividade em posições estratégicas, fatores que prejudicam a continuidade dos serviços e a preservação do conhecimento. Considerando a necessidade de uma gestão estratégica de pessoas que reduza esses riscos e favoreça um ambiente sustentável, assinale a alternativa que apresenta a abordagem mais adequada.",
    opcoes: [
      { id: "q56_a", texto: "Priorizar a reposição imediata dos profissionais desligados, mediante contratações rápidas para ocupar as posições vagas, sem aprofundar a investigação das causas da rotatividade, a fim de minimizar o impacto sobre os projetos em andamento e a continuidade operacional." },
      { id: "q56_b", texto: "Intensificar as metas de produtividade e encurtar os prazos de entrega, reforçando o senso de urgência e comprometimento coletivo, partindo-se da premissa de que a pressão por resultados atua como fator motivador e catalisador do engajamento da equipe." },
      { id: "q56_c", texto: "Reconhecer a alta rotatividade como característica própria do setor de tecnologia, mantendo os processos atuais de reposição e priorizando a cobertura imediata das demandas operacionais." },
      { id: "q56_d", texto: "Implementar um programa estruturado para investigar as causas dos desligamentos e da desmotivação, considerando carga de trabalho, reconhecimento e perspectivas de carreira, e desenvolver medidas corretivas, como redistribuição de tarefas, ações de bem-estar, feedback regular e planos de desenvolvimento individual." },
      { id: "q56_e", texto: "Manter a gestão concentrada exclusivamente nos objetivos técnicos e de infraestrutura, transferindo à área de Recursos Humanos a responsabilidade pelo clima organizacional e pela rotatividade, sem intervenção direta na dinâmica da equipe." },
    ],
  },
  {
    id: 57,
    eixoId: "E08",
    eixo: "Liderança e Competências Transversais",
    tagFonte: "TAG Macroárea: Liderança, Processos e Competências Transversais / Gestão de Equipes",
    macroarea: "Liderança, Processos e Competências Transversais",
    microarea: "Gestão de Equipes",
    enunciado: "Analise a relação entre as afirmações a seguir sobre delegação gerencial. ASSERÇÃO: A delegação eficaz de atividades constitui uma ferramenta essencial de gestão para ampliar o desempenho e desenvolver a autonomia da equipe. PORQUE — RAZÃO: A delegação permite que o gestor concentre sua atuação em atividades estratégicas de maior valor e proporciona aos integrantes da equipe oportunidades de aprendizado e crescimento previstas no Plano de Desenvolvimento Individual (PDI). A respeito dessas afirmações, assinale a alternativa correta.",
    opcoes: [
      { id: "q57_a", texto: "A asserção é verdadeira, mas a razão é falsa." },
      { id: "q57_b", texto: "A asserção e a razão são falsas." },
      { id: "q57_c", texto: "A asserção e a razão são verdadeiras, e a razão explica corretamente a asserção." },
      { id: "q57_d", texto: "A asserção é falsa, e a razão é verdadeira." },
      { id: "q57_e", texto: "A asserção e a razão são verdadeiras, mas a razão não explica a asserção." },
      { id: "q57_f", texto: "Não sei, desconheço o conteúdo.", naoSei: true },
    ],
  },
  {
    id: 58,
    eixoId: "E08",
    eixo: "Liderança e Competências Transversais",
    tagFonte: "TAG Macroárea: Liderança, Processos e Competências Transversais / Metodologias Ágeis",
    macroarea: "Liderança, Processos e Competências Transversais",
    microarea: "Metodologias Ágeis",
    enunciado: "Analise as afirmações seguintes sobre a utilização do Kanban na gestão do trabalho. I. Kanban é uma metodologia ágil que emprega um quadro visual para representar o fluxo das atividades, como To Do, Doing e Done. II. Kanban estabelece limites para o Trabalho em Progresso (WIP), orientando a equipe a concluir as tarefas iniciadas antes de assumir novas atividades. III. Kanban pode ser aplicado exclusivamente em processos de desenvolvimento de software. Assinale a alternativa correta.",
    opcoes: [
      { id: "q58_a", texto: "Todas as afirmações são verdadeiras." },
      { id: "q58_b", texto: "Apenas a afirmação I é verdadeira." },
      { id: "q58_c", texto: "As afirmações I e III são verdadeiras." },
      { id: "q58_d", texto: "As afirmações I e II são verdadeiras." },
      { id: "q58_e", texto: "Todas as afirmações são falsas." },
    ],
  },
  {
    id: 59,
    eixoId: "E08",
    eixo: "Liderança e Competências Transversais",
    tagFonte: "TAG Macroárea: Liderança, Processos e Competências Transversais / Comunicação Organizacional",
    macroarea: "Liderança, Processos e Competências Transversais",
    microarea: "Comunicação Organizacional",
    enunciado: "Na Unidade de Tecnologia da Informação e Comunicação (UTIC), a implantação de mudanças estruturais nos processos de Gerenciamento de Serviços (Service Management) requer uma estratégia de Gestão de Mudanças (Change Management) capaz de reduzir resistências e preservar a continuidade operacional. Sob a perspectiva da liderança e da comunicação organizacional, assinale a abordagem técnica adequada.",
    opcoes: [
      { id: "q59_a", texto: "Concluir a transição para os novos processos de Service Desk antes de explicar suas razões estratégicas, permitindo que a equipe compreenda os benefícios de forma empírica durante a execução das novas rotinas." },
      { id: "q59_b", texto: "Restringir a divulgação das mudanças a comunicados oficiais publicados em canais institucionais passivos, considerando que a padronização documental e a conformidade hierárquica são suficientes para assegurar a adesão da equipe." },
      { id: "q59_c", texto: "Comunicar previamente à equipe os fundamentos da mudança, oferecer suporte e capacitação, estabelecer canais para coleta de percepções e ajustar o plano de transição de acordo com os feedbacks técnicos recebidos." },
      { id: "q59_d", texto: "Substituir imediatamente os fluxos operacionais, fundamentando a transição na autoridade técnica da gestão central para evitar resistência passiva e fragmentação do conhecimento durante a consolidação das novas diretrizes." },
      { id: "q59_e", texto: "Centralizar a condução da mudança nos núcleos de coordenação técnica, dispensando mecanismos de comunicação bilateral sob o entendimento de que a autonomia gerencial deve prevalecer sobre as percepções individuais." },
      { id: "q59_f", texto: "Não sei, desconheço o conteúdo.", naoSei: true },
    ],
  },
];
